version: "3"

services:
  db:
    image: mongo:latest

  app:
    build: .
    command: "uvicorn main:app --reload"
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://db"
    volumes:
      - "./:/app:rw"
    depends_on:
      - "db"
    restart: "always"
