version: "3"

services:
  db:
    image: mongo:latest

  app:
    container_name: app
    build: .
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://db"
    volumes:
      - "./:/app:rw"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - "db"
    restart: "always"
